### ISSUE TITLE
Не получается добавить плагин.

### ISSUE THREAD

**Issue by bahmaster1** [CheeryLee/fastlane-plugin-lazurite#1]
Добрый день, подскажите пожалуйста, в чём может быть проблема?
Добавил плагин в Pluginfile:
gem "fastlane-plugin-lazurite", git: "https://github.com/CheeryLee/fastlane-plugin-lazurite" 
При попытке установить плагин
sudo fastlane add_plugin lazurite:

[09:28:07]: Installing Ruby gem 'fastlane-plugin-lazurite'...
[09:28:14]: Found gem "fastlane-plugin-fabulove" instead of the required name "fastlane-plugin-lazurite"
[09:28:15]: Successfully installed 'fastlane-plugin-lazurite'
[09:28:15]: Error loading plugin 'fastlane-plugin-lazurite': cannot load such file -- fastlane/plugin/lazurite

**Comment by CheeryLee** [comment]
Добрый день!

Команда `fastlane add_plugin` сначала попытается найти плагин в RubyGems. На данный момент он там не опубликован. Интерактивная форма предложит вам указать источник загрузки. Выберите "Git URL" и введите адрес к этому репозиторию.

Вы получите результат в Pluginfile, который указали у себя в вопросе. Это можно делать вручную без `fastlane add_plugin`: достаточно просто написать в Pluginfile

```ruby
gem "fastlane-plugin-lazurite", git: "https://github.com/CheeryLee/fastlane-plugin-lazurite.git"
```

... и Fastlane автоматически подхватит все зависимости при запуске.

**UPD:** заметил, что в readme неправильно указана ссылка на репозиторий. Поправил, спасибо за замечание.
