### ISSUE TITLE
rustore api error 413

### ISSUE THREAD

**Issue by dvnpv** [CheeryLee/fastlane-plugin-lazurite#2]
Добрый день! Спасибо за плагин!

Делаем следующее (загружаем APK, использую company_id):
![image](https://github.com/CheeryLee/fastlane-plugin-lazurite/assets/7305140/43221388-ac56-41c2-9dc2-4c4941eb782f)

авторизация проходит, черновик создается
![image](https://github.com/CheeryLee/fastlane-plugin-lazurite/assets/7305140/e8fc129e-c1db-4f35-810f-4d2a0aefbe32)

при загрузке apk получаем ошибку 413
![image](https://github.com/CheeryLee/fastlane-plugin-lazurite/assets/7305140/1f7507e2-d539-4642-b4ec-3ce4161a98f1)

что делаем не так?

**Comment by CheeryLee** [comment]
Добрый день!

В данный момент я не обладаю достаточным количеством времени для проверки текущей версии API. Однако ошибка 413 может означать, что вы пытаетесь залить слишком большой пакет на сервер RuStore. Согласно документации, максимальный размер для APK - 2.5 Гб, для AAB - 512 Мб.

**Comment by dvnpv** [comment]
Пакет у нас около 60 Мб.

В ТП Рустора ответили:
`Ошибка «413 Request Entity Too Large» может возникать из-за неверного указания versionId. В этом параметре следует указывать versionId, который возвращается при создании черновика (статья [«Создание черновика версии»](https://help.rustore.ru/rustore/for_developers/work_with_RuStore_API/publish_RuStore_API/version)). Выглядеть он может так: 243242`

может быть это наводит на какие-то идеи?

**Comment by CheeryLee** [comment]
Постараюсь проверить в ближайшее время. Спасибо за информацию.

**Comment by CheeryLee** [comment]
Добрый день!

В мастер залил потенциальный фикс проблемы. Также заметил, что отсутствовала команда отправки на модерацию. Ее тоже добавил.
Проверьте, пожалуйста, всё ли теперь работает.

**Comment by dvnpv** [comment]
Спасибо! Попробуем (вероятно, вернемся в пн-вт).

**Comment by skobelev-dmitriy** [comment]
Добрый день.  Загрузка апк вроде починилась, но теперь ошибка как раз на этапе коммита черновика.
![Screenshot_20240703_12573461](https://github.com/CheeryLee/fastlane-plugin-lazurite/assets/11031637/30918287-8fba-45d9-aaf1-f4bf60324c1f)

**Comment by CheeryLee** [comment]
Не заметил. Спасибо. Фикс залит. Попробуйте еще раз.

**Comment by skobelev-dmitriy** [comment]
Благодарю. Сейчас получилось залить и отправить на модерацию, но только после ручного удаления предыдущего активного черновика. Автоматически не получилось - [!] Draft removal failed: Request returned the error.

**Comment by skobelev-dmitriy** [comment]
Черновик не удалился из-за прав видимо. Ключ без права удаления черновика. Проверим с другим ключом

**Comment by skobelev-dmitriy** [comment]
Приветствую. Осталась еще проблема с company_id/key_id. При установке company_id(при единственном ключе) - все ок. Завели еще один ключ, установил его-  [!] Authorization failed: Request returned the error. Description: Company key not found
Попробовал вернуть на company_id - Description: Incorrect usage of companyId. Please use keyId.
Насколько понял по коду, что проблема где-то тут https://github.com/CheeryLee/fastlane-plugin-lazurite/blob/74c79fcd9080a2d34f5444ad500b19ceb67173a7/lib/fastlane/plugin/lazurite/helper/uploader.rb#L22C11-L22C20 - плагин любой ключ отправляет как company_id. Можно переделать на использование key_id, т.к. с 30 июля возможно будет использовать только его - https://www.rustore.ru/help/work-with-rustore-api/api-authorization-token

**Comment by CheeryLee** [comment]
Да, вы правы. Поменял до этого название параметра в сигнатуре, но забыл про саму авторизацию. 😥 
Фикс залит. Попробуйте еще раз.

**Comment by skobelev-dmitriy** [comment]
Благодарю. Все работает. Можно закрывать.
